services:
  - type: web
    name: tc-artikelliste
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TC_PUBLIC_BASE_URL
        value: https://tc-artikelliste.onrender.com
      - key: TC_CACHE_SECONDS
        value: "30"
      - key: TC_RSS_SOURCE
        value: https://www.bild.de/feed/alles.xml
    healthCheckPath: /healthz
